# Generated by Django 2.2.5 on 2019-09-07 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190907_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('dateAjout', models.DateField(default=datetime.datetime(2019, 9, 7, 22, 22, 52, 982719), verbose_name='Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/')),
            ],
        ),
    ]
